# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fe59cf4f8217f52cc5943dd0d29c11669f2ab2b85b993f5a9d3a194b8bf7d52d822a1be635ad555d731d6e42a9eeda84265f90c229affff3c00abbeb819f89d

test:
  secret_key_base: 3ca100d1aed5fa9a9d69db469bc462f1f90caf088a718ac97474ce02fc910b7f8af0bab27f0b6d137c100c3f9a1ea409c8d4338d15d2667f77116faec0f216d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
